# Generated by Django 5.1.4 on 2024-12-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('clicks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('dispatched', 'Dispatched'), ('returned', 'Returned'), ('delivered', 'Delivered')], default='ordered', max_length=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dash.supplier')),
            ],
        ),
    ]
